// <auto-generated />
using GorevYoneticisi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GorevYoneticisi.Migrations
{
    [DbContext(typeof(PlanDbContext))]
    partial class PlanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GorevYoneticisi.Models.Plan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baslangicTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bitisTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Planlars");
                });
#pragma warning restore 612, 618
        }
    }
}
